services:
  postgres:
    image: postgres:16
    container_name: novacart-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: novacart
      POSTGRES_USER: novacart
      POSTGRES_PASSWORD: novacart_dev_password

    ports:
      - "5433:5432"

    volumes:
      - novacart_postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novacart -d novacart"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  novacart_postgres_data: