-- ============================================================
-- NovaCart AI
-- Seed 007: Graph Relationships
-- ============================================================

BEGIN;

-- ============================================================
-- 1. ACTIVITY → ROLE
-- ============================================================

INSERT INTO activity_roles (
    activity_id,
    role_id,
    responsibility,
    importance
)
SELECT
    a.activity_id,
    r.role_id,
    x.responsibility,
    x.importance
FROM (
    VALUES

    -- Customer Acquisition
    ('ACT_CA_001', 'ROLE_MARKETING_MANAGER', 'Own campaign objectives', 95),
    ('ACT_CA_001', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Analyze campaign goals', 75),

    ('ACT_CA_002', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Analyze customer segments', 95),
    ('ACT_CA_002', 'ROLE_MARKETING_MANAGER', 'Define target segments', 80),

    ('ACT_CA_003', 'ROLE_MARKETING_MANAGER', 'Allocate acquisition budget', 95),
    ('ACT_CA_003', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Provide budget analysis', 75),

    ('ACT_CA_004', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Create campaign content', 95),
    ('ACT_CA_004', 'ROLE_MARKETING_MANAGER', 'Review campaign messaging', 60),

    ('ACT_CA_005', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Launch digital campaigns', 95),

    ('ACT_CA_006', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Monitor campaigns', 90),
    ('ACT_CA_006', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Analyze performance', 90),

    ('ACT_CA_007', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Optimize targeting', 90),
    ('ACT_CA_007', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Provide optimization insights', 80),

    ('ACT_CA_008', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Score prospects', 95),
    ('ACT_CA_008', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Use acquisition signals', 60),

    ('ACT_CA_009', 'ROLE_DIGITAL_MARKETING_SPECIALIST', 'Create personalized offers', 85),
    ('ACT_CA_009', 'ROLE_MARKETING_MANAGER', 'Approve offers', 60),

    ('ACT_CA_010', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Analyze conversion funnel', 95),
    ('ACT_CA_010', 'ROLE_MARKETING_MANAGER', 'Review funnel performance', 70),

    -- Merchandising
    ('ACT_MC_001', 'ROLE_CATALOG_SPECIALIST', 'Collect product information', 95),
    ('ACT_MC_001', 'ROLE_MERCHANDISING_MANAGER', 'Define information requirements', 60),

    ('ACT_MC_002', 'ROLE_CATALOG_SPECIALIST', 'Validate product attributes', 95),

    ('ACT_MC_003', 'ROLE_CATALOG_SPECIALIST', 'Create product listings', 95),
    ('ACT_MC_003', 'ROLE_PRODUCT_MANAGER', 'Review customer-facing information', 60),

    ('ACT_MC_004', 'ROLE_CATALOG_SPECIALIST', 'Review listing quality', 90),

    ('ACT_MC_005', 'ROLE_CATALOG_SPECIALIST', 'Categorize products', 95),
    ('ACT_MC_005', 'ROLE_MERCHANDISING_MANAGER', 'Review categorization strategy', 60),

    ('ACT_MC_006', 'ROLE_CATALOG_SPECIALIST', 'Detect catalog duplicates', 90),

    ('ACT_MC_007', 'ROLE_CATALOG_SPECIALIST', 'Maintain catalog information', 95),

    ('ACT_MC_008', 'ROLE_CATALOG_SPECIALIST', 'Monitor catalog quality', 90),
    ('ACT_MC_008', 'ROLE_PRODUCT_MANAGER', 'Review catalog performance', 55),

    ('ACT_MC_009', 'ROLE_PRICING_ANALYST', 'Analyze competitor prices', 95),
    ('ACT_MC_009', 'ROLE_MERCHANDISING_MANAGER', 'Review market pricing', 70),

    ('ACT_MC_010', 'ROLE_PRICING_ANALYST', 'Calculate price recommendations', 95),

    ('ACT_MC_011', 'ROLE_PRICING_ANALYST', 'Prepare pricing recommendations', 90),
    ('ACT_MC_011', 'ROLE_MERCHANDISING_MANAGER', 'Approve pricing changes', 90),

    ('ACT_MC_012', 'ROLE_CATALOG_SPECIALIST', 'Publish approved prices', 90),

    ('ACT_MC_013', 'ROLE_MERCHANDISING_MANAGER', 'Analyze product demand', 85),
    ('ACT_MC_013', 'ROLE_PRICING_ANALYST', 'Provide demand analysis', 75),

    ('ACT_MC_014', 'ROLE_MERCHANDISING_MANAGER', 'Identify assortment gaps', 90),
    ('ACT_MC_014', 'ROLE_PRODUCT_MANAGER', 'Evaluate assortment gaps', 80),

    ('ACT_MC_015', 'ROLE_MERCHANDISING_MANAGER', 'Recommend assortment', 95),
    ('ACT_MC_015', 'ROLE_PRODUCT_MANAGER', 'Review assortment strategy', 85),

    -- Order Management
    ('ACT_OM_001', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Capture orders', 95),

    ('ACT_OM_002', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Create order records', 95),

    ('ACT_OM_003', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Confirm order details', 90),

    ('ACT_OM_004', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Validate customer information', 95),

    ('ACT_OM_005', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Check inventory', 90),
    ('ACT_OM_005', 'ROLE_ORDER_ANALYST', 'Analyze inventory availability', 70),

    ('ACT_OM_006', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Validate pricing', 90),

    ('ACT_OM_007', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Release orders', 95),

    ('ACT_OM_008', 'ROLE_ORDER_ANALYST', 'Prioritize orders', 90),
    ('ACT_OM_008', 'ROLE_ORDER_MANAGER', 'Approve prioritization rules', 70),

    ('ACT_OM_009', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Resolve order exceptions', 95),
    ('ACT_OM_009', 'ROLE_ORDER_ANALYST', 'Analyze exception patterns', 70),

    ('ACT_OM_010', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Track order status', 95),

    ('ACT_OM_011', 'ROLE_ORDER_ANALYST', 'Detect delayed orders', 90),
    ('ACT_OM_011', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Investigate delays', 80),

    ('ACT_OM_012', 'ROLE_ORDER_OPERATIONS_SPECIALIST', 'Communicate order updates', 90),

    -- Fulfillment
    ('ACT_FD_001', 'ROLE_INVENTORY_PLANNER', 'Analyze available inventory', 95),
    ('ACT_FD_001', 'ROLE_FULFILLMENT_MANAGER', 'Review inventory availability', 70),

    ('ACT_FD_002', 'ROLE_INVENTORY_PLANNER', 'Allocate inventory', 95),
    ('ACT_FD_002', 'ROLE_FULFILLMENT_MANAGER', 'Approve allocation strategy', 70),

    ('ACT_FD_003', 'ROLE_INVENTORY_PLANNER', 'Resolve shortages', 90),
    ('ACT_FD_003', 'ROLE_FULFILLMENT_MANAGER', 'Manage shortage escalation', 80),

    ('ACT_FD_004', 'ROLE_FULFILLMENT_MANAGER', 'Generate picking workflow', 80),
    ('ACT_FD_004', 'ROLE_WAREHOUSE_ASSOCIATE', 'Follow picking instructions', 85),

    ('ACT_FD_005', 'ROLE_WAREHOUSE_ASSOCIATE', 'Pick products', 100),

    ('ACT_FD_006', 'ROLE_WAREHOUSE_ASSOCIATE', 'Verify picked products', 95),

    ('ACT_FD_007', 'ROLE_WAREHOUSE_ASSOCIATE', 'Pack orders', 100),

    ('ACT_FD_008', 'ROLE_LOGISTICS_COORDINATOR', 'Generate shipment information', 95),

    ('ACT_FD_009', 'ROLE_LOGISTICS_COORDINATOR', 'Select logistics provider', 90),
    ('ACT_FD_009', 'ROLE_LAST_MILE_ANALYST', 'Analyze carrier performance', 70),

    ('ACT_FD_010', 'ROLE_LOGISTICS_COORDINATOR', 'Generate shipping labels', 95),

    ('ACT_FD_011', 'ROLE_LAST_MILE_ANALYST', 'Monitor deliveries', 95),
    ('ACT_FD_011', 'ROLE_LOGISTICS_COORDINATOR', 'Coordinate delivery status', 80),

    ('ACT_FD_012', 'ROLE_LAST_MILE_ANALYST', 'Predict delivery delays', 95),

    ('ACT_FD_013', 'ROLE_LOGISTICS_COORDINATOR', 'Resolve delivery exceptions', 90),

    -- Payments & Fraud
    ('ACT_PF_001', 'ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'Validate payment details', 95),

    ('ACT_PF_002', 'ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'Authorize payments', 95),

    ('ACT_PF_003', 'ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'Resolve payment failures', 90),

    ('ACT_PF_004', 'ROLE_FRAUD_ANALYST', 'Calculate transaction risk', 95),
    ('ACT_PF_004', 'ROLE_FRAUD_MANAGER', 'Review risk models', 70),

    ('ACT_PF_005', 'ROLE_FRAUD_ANALYST', 'Investigate suspicious transactions', 100),

    ('ACT_PF_006', 'ROLE_FRAUD_ANALYST', 'Escalate high-risk transactions', 90),
    ('ACT_PF_006', 'ROLE_FRAUD_MANAGER', 'Review escalations', 85),

    ('ACT_PF_007', 'ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'Match payments and orders', 100),

    ('ACT_PF_008', 'ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'Detect discrepancies', 95),

    ('ACT_PF_009', 'ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'Resolve discrepancies', 95),

    -- Customer Service
    ('ACT_CS_001', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Receive inquiries', 95),

    ('ACT_CS_002', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Classify inquiries', 90),
    ('ACT_CS_002', 'ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'Analyze inquiry categories', 70),

    ('ACT_CS_003', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Route inquiries', 90),

    ('ACT_CS_004', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Investigate customer issues', 95),

    ('ACT_CS_005', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Recommend resolutions', 90),

    ('ACT_CS_006', 'ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'Resolve customer issues', 100),
    ('ACT_CS_006', 'ROLE_CUSTOMER_SERVICE_MANAGER', 'Handle escalated cases', 80),

    ('ACT_CS_007', 'ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'Collect customer feedback', 90),

    ('ACT_CS_008', 'ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'Analyze customer sentiment', 95),

    ('ACT_CS_009', 'ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'Identify recurring problems', 95),
    ('ACT_CS_009', 'ROLE_CUSTOMER_SERVICE_MANAGER', 'Prioritize service improvements', 70),

    -- Returns
    ('ACT_PR_001', 'ROLE_RETURNS_SPECIALIST', 'Receive return requests', 95),

    ('ACT_PR_002', 'ROLE_RETURNS_SPECIALIST', 'Validate return eligibility', 95),

    ('ACT_PR_003', 'ROLE_RETURNS_SPECIALIST', 'Approve or reject returns', 90),

    ('ACT_PR_004', 'ROLE_REFUNDS_SPECIALIST', 'Validate refund amount', 95),

    ('ACT_PR_005', 'ROLE_REFUNDS_SPECIALIST', 'Process refunds', 100),

    ('ACT_PR_006', 'ROLE_REFUNDS_SPECIALIST', 'Reconcile refunds', 95),

    ('ACT_PR_007', 'ROLE_RETURNS_SPECIALIST', 'Validate exchanges', 95),

    ('ACT_PR_008', 'ROLE_RETURNS_SPECIALIST', 'Allocate replacement products', 85),
    ('ACT_PR_008', 'ROLE_INVENTORY_PLANNER', 'Provide inventory availability', 75),

    ('ACT_PR_009', 'ROLE_RETURNS_SPECIALIST', 'Process exchanges', 95),

    ('ACT_PR_010', 'ROLE_CUSTOMER_RETENTION_MANAGER', 'Identify at-risk customers', 95),
    ('ACT_PR_010', 'ROLE_CUSTOMER_ACQUISITION_ANALYST', 'Analyze churn signals', 75),

    ('ACT_PR_011', 'ROLE_CUSTOMER_RETENTION_MANAGER', 'Recommend retention actions', 95),

    ('ACT_PR_012', 'ROLE_CUSTOMER_RETENTION_MANAGER', 'Launch retention campaigns', 95),

    -- Cross-functional analytics
    ('ACT_CA_002', 'ROLE_DATA_ANALYST', 'Analyze customer data', 80),
    ('ACT_CA_006', 'ROLE_DATA_ANALYST', 'Analyze marketing metrics', 85),
    ('ACT_MC_013', 'ROLE_DATA_ANALYST', 'Analyze demand data', 80),
    ('ACT_OM_011', 'ROLE_DATA_ANALYST', 'Analyze order delays', 80),
    ('ACT_FD_012', 'ROLE_DATA_ANALYST', 'Analyze delivery patterns', 80),
    ('ACT_PF_004', 'ROLE_DATA_ANALYST', 'Analyze fraud signals', 80),
    ('ACT_CS_008', 'ROLE_DATA_ANALYST', 'Analyze customer sentiment data', 80),
    ('ACT_PR_010', 'ROLE_DATA_ANALYST', 'Analyze churn patterns', 85)

) AS x(
    activity_code,
    role_code,
    responsibility,
    importance
)
JOIN activities a
    ON a.activity_code = x.activity_code
JOIN roles r
    ON r.role_code = x.role_code

ON CONFLICT (activity_id, role_id) DO NOTHING;


-- ============================================================
-- 2. ROLE → SKILL
-- ============================================================

INSERT INTO role_skills (
    role_id,
    skill_id,
    proficiency_required,
    importance
)
SELECT
    r.role_id,
    s.skill_id,
    x.proficiency_required,
    x.importance
FROM (
    VALUES

    -- Marketing Manager
    ('ROLE_MARKETING_MANAGER', 'SKILL_BUSINESS_STRATEGY', 'ADVANCED', 95),
    ('ROLE_MARKETING_MANAGER', 'SKILL_DIGITAL_MARKETING', 'ADVANCED', 90),
    ('ROLE_MARKETING_MANAGER', 'SKILL_CAMPAIGN_MANAGEMENT', 'ADVANCED', 95),
    ('ROLE_MARKETING_MANAGER', 'SKILL_MARKET_ANALYSIS', 'ADVANCED', 85),
    ('ROLE_MARKETING_MANAGER', 'SKILL_CUSTOMER_ANALYSIS', 'INTERMEDIATE', 80),
    ('ROLE_MARKETING_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),
    ('ROLE_MARKETING_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 90),

    -- Digital Marketing Specialist
    ('ROLE_DIGITAL_MARKETING_SPECIALIST', 'SKILL_DIGITAL_MARKETING', 'ADVANCED', 95),
    ('ROLE_DIGITAL_MARKETING_SPECIALIST', 'SKILL_CAMPAIGN_MANAGEMENT', 'ADVANCED', 95),
    ('ROLE_DIGITAL_MARKETING_SPECIALIST', 'SKILL_MARKETING_ANALYTICS', 'INTERMEDIATE', 85),
    ('ROLE_DIGITAL_MARKETING_SPECIALIST', 'SKILL_CONTENT_CREATION', 'ADVANCED', 85),
    ('ROLE_DIGITAL_MARKETING_SPECIALIST', 'SKILL_CUSTOMER_SEGMENTATION', 'INTERMEDIATE', 80),

    -- Customer Acquisition Analyst
    ('ROLE_CUSTOMER_ACQUISITION_ANALYST', 'SKILL_CUSTOMER_ANALYSIS', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_ACQUISITION_ANALYST', 'SKILL_CUSTOMER_SEGMENTATION', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_ACQUISITION_ANALYST', 'SKILL_MARKETING_ANALYTICS', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_ACQUISITION_ANALYST', 'SKILL_STATISTICS', 'INTERMEDIATE', 80),
    ('ROLE_CUSTOMER_ACQUISITION_ANALYST', 'SKILL_SQL', 'INTERMEDIATE', 85),

    -- Merchandising Manager
    ('ROLE_MERCHANDISING_MANAGER', 'SKILL_MERCHANDISING', 'ADVANCED', 95),
    ('ROLE_MERCHANDISING_MANAGER', 'SKILL_PRODUCT_MANAGEMENT', 'ADVANCED', 85),
    ('ROLE_MERCHANDISING_MANAGER', 'SKILL_DEMAND_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_MERCHANDISING_MANAGER', 'SKILL_MARKET_ANALYSIS', 'ADVANCED', 85),
    ('ROLE_MERCHANDISING_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),

    -- Catalog Specialist
    ('ROLE_CATALOG_SPECIALIST', 'SKILL_CATALOG_MANAGEMENT', 'ADVANCED', 100),
    ('ROLE_CATALOG_SPECIALIST', 'SKILL_PRODUCT_DATA_QUALITY', 'ADVANCED', 95),
    ('ROLE_CATALOG_SPECIALIST', 'SKILL_DATA_MODELING', 'INTERMEDIATE', 65),
    ('ROLE_CATALOG_SPECIALIST', 'SKILL_DATA_ANALYSIS', 'INTERMEDIATE', 70),

    -- Pricing Analyst
    ('ROLE_PRICING_ANALYST', 'SKILL_PRICING_ANALYSIS', 'ADVANCED', 100),
    ('ROLE_PRICING_ANALYST', 'SKILL_MARKET_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_PRICING_ANALYST', 'SKILL_DEMAND_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_PRICING_ANALYST', 'SKILL_STATISTICS', 'ADVANCED', 85),
    ('ROLE_PRICING_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_PRICING_ANALYST', 'SKILL_SQL', 'INTERMEDIATE', 75),

    -- Product Manager
    ('ROLE_PRODUCT_MANAGER', 'SKILL_PRODUCT_MANAGEMENT', 'ADVANCED', 100),
    ('ROLE_PRODUCT_MANAGER', 'SKILL_CUSTOMER_ANALYSIS', 'ADVANCED', 85),
    ('ROLE_PRODUCT_MANAGER', 'SKILL_MARKET_ANALYSIS', 'ADVANCED', 85),
    ('ROLE_PRODUCT_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),
    ('ROLE_PRODUCT_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 90),

    -- Order Operations Specialist
    ('ROLE_ORDER_OPERATIONS_SPECIALIST', 'SKILL_ORDER_MANAGEMENT', 'ADVANCED', 100),
    ('ROLE_ORDER_OPERATIONS_SPECIALIST', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 90),
    ('ROLE_ORDER_OPERATIONS_SPECIALIST', 'SKILL_CUSTOMER_COMMUNICATION', 'INTERMEDIATE', 70),
    ('ROLE_ORDER_OPERATIONS_SPECIALIST', 'SKILL_OPERATIONAL_PLANNING', 'INTERMEDIATE', 75),

    -- Order Analyst
    ('ROLE_ORDER_ANALYST', 'SKILL_ORDER_ANALYTICS', 'ADVANCED', 100),
    ('ROLE_ORDER_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 95),
    ('ROLE_ORDER_ANALYST', 'SKILL_SQL', 'ADVANCED', 90),
    ('ROLE_ORDER_ANALYST', 'SKILL_STATISTICS', 'INTERMEDIATE', 80),
    ('ROLE_ORDER_ANALYST', 'SKILL_EXCEPTION_HANDLING', 'INTERMEDIATE', 70),

    -- Order Manager
    ('ROLE_ORDER_MANAGER', 'SKILL_ORDER_MANAGEMENT', 'ADVANCED', 95),
    ('ROLE_ORDER_MANAGER', 'SKILL_OPERATIONAL_PLANNING', 'ADVANCED', 90),
    ('ROLE_ORDER_MANAGER', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 85),
    ('ROLE_ORDER_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),
    ('ROLE_ORDER_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 85),

    -- Fulfillment Manager
    ('ROLE_FULFILLMENT_MANAGER', 'SKILL_INVENTORY_MANAGEMENT', 'ADVANCED', 95),
    ('ROLE_FULFILLMENT_MANAGER', 'SKILL_WAREHOUSE_OPERATIONS', 'ADVANCED', 90),
    ('ROLE_FULFILLMENT_MANAGER', 'SKILL_SUPPLY_CHAIN_ANALYTICS', 'ADVANCED', 90),
    ('ROLE_FULFILLMENT_MANAGER', 'SKILL_OPERATIONAL_PLANNING', 'ADVANCED', 90),
    ('ROLE_FULFILLMENT_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 90),

    -- Inventory Planner
    ('ROLE_INVENTORY_PLANNER', 'SKILL_INVENTORY_PLANNING', 'ADVANCED', 100),
    ('ROLE_INVENTORY_PLANNER', 'SKILL_INVENTORY_MANAGEMENT', 'ADVANCED', 95),
    ('ROLE_INVENTORY_PLANNER', 'SKILL_DEMAND_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_INVENTORY_PLANNER', 'SKILL_SUPPLY_CHAIN_ANALYTICS', 'ADVANCED', 90),
    ('ROLE_INVENTORY_PLANNER', 'SKILL_STATISTICS', 'INTERMEDIATE', 75),

    -- Warehouse Associate
    ('ROLE_WAREHOUSE_ASSOCIATE', 'SKILL_WAREHOUSE_OPERATIONS', 'ADVANCED', 100),
    ('ROLE_WAREHOUSE_ASSOCIATE', 'SKILL_INVENTORY_MANAGEMENT', 'INTERMEDIATE', 75),
    ('ROLE_WAREHOUSE_ASSOCIATE', 'SKILL_EXCEPTION_HANDLING', 'INTERMEDIATE', 65),

    -- Logistics Coordinator
    ('ROLE_LOGISTICS_COORDINATOR', 'SKILL_LOGISTICS_MANAGEMENT', 'ADVANCED', 100),
    ('ROLE_LOGISTICS_COORDINATOR', 'SKILL_ROUTE_OPTIMIZATION', 'INTERMEDIATE', 80),
    ('ROLE_LOGISTICS_COORDINATOR', 'SKILL_OPERATIONAL_PLANNING', 'ADVANCED', 85),
    ('ROLE_LOGISTICS_COORDINATOR', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 85),

    -- Last Mile Analyst
    ('ROLE_LAST_MILE_ANALYST', 'SKILL_SUPPLY_CHAIN_ANALYTICS', 'ADVANCED', 95),
    ('ROLE_LAST_MILE_ANALYST', 'SKILL_ROUTE_OPTIMIZATION', 'ADVANCED', 90),
    ('ROLE_LAST_MILE_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_LAST_MILE_ANALYST', 'SKILL_STATISTICS', 'INTERMEDIATE', 80),
    ('ROLE_LAST_MILE_ANALYST', 'SKILL_SQL', 'INTERMEDIATE', 75),

    -- Payment Operations
    ('ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'SKILL_PAYMENT_OPERATIONS', 'ADVANCED', 100),
    ('ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 80),
    ('ROLE_PAYMENT_OPERATIONS_SPECIALIST', 'SKILL_TRANSACTION_MONITORING', 'INTERMEDIATE', 80),

    -- Fraud Analyst
    ('ROLE_FRAUD_ANALYST', 'SKILL_FRAUD_ANALYSIS', 'ADVANCED', 100),
    ('ROLE_FRAUD_ANALYST', 'SKILL_RISK_ASSESSMENT', 'ADVANCED', 95),
    ('ROLE_FRAUD_ANALYST', 'SKILL_TRANSACTION_MONITORING', 'ADVANCED', 95),
    ('ROLE_FRAUD_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_FRAUD_ANALYST', 'SKILL_STATISTICS', 'INTERMEDIATE', 80),
    ('ROLE_FRAUD_ANALYST', 'SKILL_SQL', 'INTERMEDIATE', 75),

    -- Fraud Manager
    ('ROLE_FRAUD_MANAGER', 'SKILL_FRAUD_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_FRAUD_MANAGER', 'SKILL_RISK_ASSESSMENT', 'ADVANCED', 100),
    ('ROLE_FRAUD_MANAGER', 'SKILL_MODEL_RISK', 'ADVANCED', 85),
    ('ROLE_FRAUD_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),
    ('ROLE_FRAUD_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 80),

    -- Financial Reconciliation
    ('ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'SKILL_FINANCIAL_RECONCILIATION', 'ADVANCED', 100),
    ('ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'SKILL_SQL', 'ADVANCED', 90),
    ('ROLE_FINANCIAL_RECONCILIATION_ANALYST', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 80),

    -- Customer Support
    ('ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'SKILL_CUSTOMER_SERVICE', 'ADVANCED', 100),
    ('ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'SKILL_CUSTOMER_COMMUNICATION', 'ADVANCED', 100),
    ('ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'SKILL_ISSUE_RESOLUTION', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_SUPPORT_SPECIALIST', 'SKILL_EXCEPTION_HANDLING', 'INTERMEDIATE', 70),

    -- Customer Experience
    ('ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'SKILL_CUSTOMER_EXPERIENCE', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'SKILL_SENTIMENT_ANALYSIS', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'SKILL_CUSTOMER_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_EXPERIENCE_ANALYST', 'SKILL_SQL', 'INTERMEDIATE', 75),

    -- Customer Service Manager
    ('ROLE_CUSTOMER_SERVICE_MANAGER', 'SKILL_CUSTOMER_SERVICE', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_SERVICE_MANAGER', 'SKILL_CUSTOMER_EXPERIENCE', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_SERVICE_MANAGER', 'SKILL_ISSUE_RESOLUTION', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_SERVICE_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_SERVICE_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 85),

    -- Returns Specialist
    ('ROLE_RETURNS_SPECIALIST', 'SKILL_RETURNS_MANAGEMENT', 'ADVANCED', 100),
    ('ROLE_RETURNS_SPECIALIST', 'SKILL_EXCEPTION_HANDLING', 'ADVANCED', 85),
    ('ROLE_RETURNS_SPECIALIST', 'SKILL_CUSTOMER_SERVICE', 'ADVANCED', 85),
    ('ROLE_RETURNS_SPECIALIST', 'SKILL_ISSUE_RESOLUTION', 'ADVANCED', 80),

    -- Refund Specialist
    ('ROLE_REFUNDS_SPECIALIST', 'SKILL_REFUND_PROCESSING', 'ADVANCED', 100),
    ('ROLE_REFUNDS_SPECIALIST', 'SKILL_FINANCIAL_RECONCILIATION', 'ADVANCED', 90),
    ('ROLE_REFUNDS_SPECIALIST', 'SKILL_PAYMENT_OPERATIONS', 'ADVANCED', 85),
    ('ROLE_REFUNDS_SPECIALIST', 'SKILL_EXCEPTION_HANDLING', 'INTERMEDIATE', 70),

    -- Retention Manager
    ('ROLE_CUSTOMER_RETENTION_MANAGER', 'SKILL_CUSTOMER_RETENTION', 'ADVANCED', 100),
    ('ROLE_CUSTOMER_RETENTION_MANAGER', 'SKILL_CHURN_ANALYSIS', 'ADVANCED', 95),
    ('ROLE_CUSTOMER_RETENTION_MANAGER', 'SKILL_CUSTOMER_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_CUSTOMER_RETENTION_MANAGER', 'SKILL_MARKETING_ANALYTICS', 'INTERMEDIATE', 75),
    ('ROLE_CUSTOMER_RETENTION_MANAGER', 'SKILL_DECISION_MAKING', 'ADVANCED', 90),

    -- Data Analyst
    ('ROLE_DATA_ANALYST', 'SKILL_SQL', 'ADVANCED', 100),
    ('ROLE_DATA_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 100),
    ('ROLE_DATA_ANALYST', 'SKILL_DATA_VISUALIZATION', 'ADVANCED', 90),
    ('ROLE_DATA_ANALYST', 'SKILL_STATISTICS', 'ADVANCED', 90),
    ('ROLE_DATA_ANALYST', 'SKILL_PYTHON', 'ADVANCED', 90),

    -- Business Analyst
    ('ROLE_BUSINESS_ANALYST', 'SKILL_PROCESS_ANALYSIS', 'ADVANCED', 100),
    ('ROLE_BUSINESS_ANALYST', 'SKILL_BUSINESS_STRATEGY', 'INTERMEDIATE', 80),
    ('ROLE_BUSINESS_ANALYST', 'SKILL_DATA_ANALYSIS', 'ADVANCED', 90),
    ('ROLE_BUSINESS_ANALYST', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 90),
    ('ROLE_BUSINESS_ANALYST', 'SKILL_DECISION_MAKING', 'ADVANCED', 85),

    -- AI Automation Specialist
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_AI_LITERACY', 'ADVANCED', 100),
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_AI_WORKFLOW_DESIGN', 'ADVANCED', 100),
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_AUTOMATION_DESIGN', 'ADVANCED', 100),
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_PROMPT_ENGINEERING', 'ADVANCED', 80),
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_AI_EVALUATION', 'ADVANCED', 90),
    ('ROLE_AI_AUTOMATION_SPECIALIST', 'SKILL_DATA_ENGINEERING', 'INTERMEDIATE', 75),

    -- AI Product Manager
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_AI_TRANSFORMATION', 'ADVANCED', 100),
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_AI_LITERACY', 'ADVANCED', 100),
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_AI_WORKFLOW_DESIGN', 'ADVANCED', 90),
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_PRODUCT_MANAGEMENT', 'ADVANCED', 90),
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_AI_GOVERNANCE', 'ADVANCED', 85),
    ('ROLE_AI_PRODUCT_MANAGER', 'SKILL_STAKEHOLDER_MANAGEMENT', 'ADVANCED', 90)

) AS x(
    role_code,
    skill_code,
    proficiency_required,
    importance
)
JOIN roles r
    ON r.role_code = x.role_code
JOIN skills s
    ON s.skill_code = x.skill_code

ON CONFLICT (role_id, skill_id) DO NOTHING;


-- ============================================================
-- 3. ACTIVITY → SKILL
-- ============================================================

INSERT INTO activity_skills (
    activity_id,
    skill_id,
    relevance
)
SELECT
    a.activity_id,
    s.skill_id,
    x.relevance
FROM (
    VALUES

    -- Marketing
    ('ACT_CA_001', 'SKILL_CAMPAIGN_MANAGEMENT', 95),
    ('ACT_CA_001', 'SKILL_BUSINESS_STRATEGY', 80),
    ('ACT_CA_002', 'SKILL_CUSTOMER_SEGMENTATION', 100),
    ('ACT_CA_002', 'SKILL_CUSTOMER_ANALYSIS', 95),
    ('ACT_CA_003', 'SKILL_CAMPAIGN_MANAGEMENT', 90),
    ('ACT_CA_003', 'SKILL_DATA_ANALYSIS', 75),
    ('ACT_CA_004', 'SKILL_CONTENT_CREATION', 100),
    ('ACT_CA_004', 'SKILL_DIGITAL_MARKETING', 90),
    ('ACT_CA_005', 'SKILL_DIGITAL_MARKETING', 100),
    ('ACT_CA_006', 'SKILL_MARKETING_ANALYTICS', 100),
    ('ACT_CA_006', 'SKILL_DATA_ANALYSIS', 90),
    ('ACT_CA_007', 'SKILL_MARKETING_ANALYTICS', 95),
    ('ACT_CA_007', 'SKILL_CUSTOMER_SEGMENTATION', 85),
    ('ACT_CA_008', 'SKILL_CUSTOMER_ANALYSIS', 95),
    ('ACT_CA_008', 'SKILL_STATISTICS', 80),
    ('ACT_CA_009', 'SKILL_CUSTOMER_SEGMENTATION', 95),
    ('ACT_CA_009', 'SKILL_DIGITAL_MARKETING', 85),
    ('ACT_CA_010', 'SKILL_MARKETING_ANALYTICS', 95),
    ('ACT_CA_010', 'SKILL_DATA_ANALYSIS', 90),

    -- Merchandising
    ('ACT_MC_001', 'SKILL_CATALOG_MANAGEMENT', 95),
    ('ACT_MC_001', 'SKILL_PRODUCT_DATA_QUALITY', 90),
    ('ACT_MC_002', 'SKILL_PRODUCT_DATA_QUALITY', 100),
    ('ACT_MC_003', 'SKILL_CATALOG_MANAGEMENT', 100),
    ('ACT_MC_004', 'SKILL_PRODUCT_DATA_QUALITY', 95),
    ('ACT_MC_005', 'SKILL_CATALOG_MANAGEMENT', 95),
    ('ACT_MC_006', 'SKILL_PRODUCT_DATA_QUALITY', 100),
    ('ACT_MC_007', 'SKILL_CATALOG_MANAGEMENT', 95),
    ('ACT_MC_008', 'SKILL_PRODUCT_DATA_QUALITY', 90),
    ('ACT_MC_009', 'SKILL_PRICING_ANALYSIS', 100),
    ('ACT_MC_009', 'SKILL_MARKET_ANALYSIS', 95),
    ('ACT_MC_010', 'SKILL_PRICING_ANALYSIS', 100),
    ('ACT_MC_010', 'SKILL_DEMAND_ANALYSIS', 90),
    ('ACT_MC_011', 'SKILL_PRICING_ANALYSIS', 100),
    ('ACT_MC_012', 'SKILL_CATALOG_MANAGEMENT', 85),
    ('ACT_MC_013', 'SKILL_DEMAND_ANALYSIS', 100),
    ('ACT_MC_013', 'SKILL_DATA_ANALYSIS', 90),
    ('ACT_MC_014', 'SKILL_DEMAND_ANALYSIS', 95),
    ('ACT_MC_015', 'SKILL_MERCHANDISING', 100),
    ('ACT_MC_015', 'SKILL_DEMAND_ANALYSIS', 90),

    -- Orders
    ('ACT_OM_001', 'SKILL_ORDER_MANAGEMENT', 100),
    ('ACT_OM_002', 'SKILL_ORDER_MANAGEMENT', 100),
    ('ACT_OM_003', 'SKILL_ORDER_MANAGEMENT', 95),
    ('ACT_OM_004', 'SKILL_ORDER_MANAGEMENT', 90),
    ('ACT_OM_005', 'SKILL_INVENTORY_MANAGEMENT', 90),
    ('ACT_OM_006', 'SKILL_ORDER_MANAGEMENT', 90),
    ('ACT_OM_007', 'SKILL_ORDER_MANAGEMENT', 100),
    ('ACT_OM_008', 'SKILL_OPERATIONAL_PLANNING', 90),
    ('ACT_OM_008', 'SKILL_ORDER_ANALYTICS', 85),
    ('ACT_OM_009', 'SKILL_EXCEPTION_HANDLING', 100),
    ('ACT_OM_009', 'SKILL_ORDER_MANAGEMENT', 90),
    ('ACT_OM_010', 'SKILL_ORDER_MANAGEMENT', 95),
    ('ACT_OM_011', 'SKILL_ORDER_ANALYTICS', 100),
    ('ACT_OM_011', 'SKILL_DATA_ANALYSIS', 90),
    ('ACT_OM_012', 'SKILL_CUSTOMER_COMMUNICATION', 90),

    -- Fulfillment
    ('ACT_FD_001', 'SKILL_INVENTORY_MANAGEMENT', 100),
    ('ACT_FD_002', 'SKILL_INVENTORY_PLANNING', 100),
    ('ACT_FD_002', 'SKILL_INVENTORY_MANAGEMENT', 95),
    ('ACT_FD_003', 'SKILL_EXCEPTION_HANDLING', 95),
    ('ACT_FD_004', 'SKILL_WAREHOUSE_OPERATIONS', 90),
    ('ACT_FD_004', 'SKILL_OPERATIONAL_PLANNING', 85),
    ('ACT_FD_005', 'SKILL_WAREHOUSE_OPERATIONS', 100),
    ('ACT_FD_006', 'SKILL_WAREHOUSE_OPERATIONS', 95),
    ('ACT_FD_007', 'SKILL_WAREHOUSE_OPERATIONS', 100),
    ('ACT_FD_008', 'SKILL_LOGISTICS_MANAGEMENT', 100),
    ('ACT_FD_009', 'SKILL_LOGISTICS_MANAGEMENT', 95),
    ('ACT_FD_009', 'SKILL_ROUTE_OPTIMIZATION', 90),
    ('ACT_FD_010', 'SKILL_LOGISTICS_MANAGEMENT', 90),
    ('ACT_FD_011', 'SKILL_SUPPLY_CHAIN_ANALYTICS', 95),
    ('ACT_FD_012', 'SKILL_ROUTE_OPTIMIZATION', 95),
    ('ACT_FD_012', 'SKILL_STATISTICS', 80),
    ('ACT_FD_013', 'SKILL_EXCEPTION_HANDLING', 100),

    -- Payments & Fraud
    ('ACT_PF_001', 'SKILL_PAYMENT_OPERATIONS', 100),
    ('ACT_PF_002', 'SKILL_PAYMENT_OPERATIONS', 100),
    ('ACT_PF_003', 'SKILL_PAYMENT_OPERATIONS', 95),
    ('ACT_PF_003', 'SKILL_EXCEPTION_HANDLING', 85),
    ('ACT_PF_004', 'SKILL_FRAUD_ANALYSIS', 100),
    ('ACT_PF_004', 'SKILL_RISK_ASSESSMENT', 100),
    ('ACT_PF_005', 'SKILL_FRAUD_ANALYSIS', 100),
    ('ACT_PF_005', 'SKILL_TRANSACTION_MONITORING', 95),
    ('ACT_PF_006', 'SKILL_RISK_ASSESSMENT', 100),
    ('ACT_PF_007', 'SKILL_FINANCIAL_RECONCILIATION', 100),
    ('ACT_PF_008', 'SKILL_FINANCIAL_RECONCILIATION', 100),
    ('ACT_PF_008', 'SKILL_DATA_ANALYSIS', 85),
    ('ACT_PF_009', 'SKILL_FINANCIAL_RECONCILIATION', 100),
    ('ACT_PF_009', 'SKILL_EXCEPTION_HANDLING', 90),

    -- Customer Service
    ('ACT_CS_001', 'SKILL_CUSTOMER_SERVICE', 100),
    ('ACT_CS_001', 'SKILL_CUSTOMER_COMMUNICATION', 100),
    ('ACT_CS_002', 'SKILL_CUSTOMER_SERVICE', 90),
    ('ACT_CS_002', 'SKILL_CUSTOMER_ANALYSIS', 80),
    ('ACT_CS_003', 'SKILL_CUSTOMER_SERVICE', 90),
    ('ACT_CS_004', 'SKILL_ISSUE_RESOLUTION', 100),
    ('ACT_CS_004', 'SKILL_CUSTOMER_SERVICE', 95),
    ('ACT_CS_005', 'SKILL_ISSUE_RESOLUTION', 100),
    ('ACT_CS_005', 'SKILL_DECISION_MAKING', 85),
    ('ACT_CS_006', 'SKILL_ISSUE_RESOLUTION', 100),
    ('ACT_CS_006', 'SKILL_CUSTOMER_SERVICE', 100),
    ('ACT_CS_007', 'SKILL_CUSTOMER_EXPERIENCE', 90),
    ('ACT_CS_008', 'SKILL_SENTIMENT_ANALYSIS', 100),
    ('ACT_CS_008', 'SKILL_DATA_ANALYSIS', 90),
    ('ACT_CS_009', 'SKILL_SENTIMENT_ANALYSIS', 90),
    ('ACT_CS_009', 'SKILL_CUSTOMER_EXPERIENCE', 90),

    -- Returns
    ('ACT_PR_001', 'SKILL_RETURNS_MANAGEMENT', 100),
    ('ACT_PR_002', 'SKILL_RETURNS_MANAGEMENT', 100),
    ('ACT_PR_003', 'SKILL_DECISION_MAKING', 90),
    ('ACT_PR_003', 'SKILL_RETURNS_MANAGEMENT', 90),
    ('ACT_PR_004', 'SKILL_REFUND_PROCESSING', 100),
    ('ACT_PR_005', 'SKILL_REFUND_PROCESSING', 100),
    ('ACT_PR_006', 'SKILL_FINANCIAL_RECONCILIATION', 100),
    ('ACT_PR_007', 'SKILL_RETURNS_MANAGEMENT', 100),
    ('ACT_PR_008', 'SKILL_INVENTORY_MANAGEMENT', 90),
    ('ACT_PR_009', 'SKILL_RETURNS_MANAGEMENT', 100),
    ('ACT_PR_010', 'SKILL_CHURN_ANALYSIS', 100),
    ('ACT_PR_010', 'SKILL_CUSTOMER_ANALYSIS', 95),
    ('ACT_PR_011', 'SKILL_CUSTOMER_RETENTION', 100),
    ('ACT_PR_011', 'SKILL_CUSTOMER_ANALYSIS', 90),
    ('ACT_PR_012', 'SKILL_CUSTOMER_RETENTION', 95),
    ('ACT_PR_012', 'SKILL_CAMPAIGN_MANAGEMENT', 80)

) AS x(
    activity_code,
    skill_code,
    relevance
)
JOIN activities a
    ON a.activity_code = x.activity_code
JOIN skills s
    ON s.skill_code = x.skill_code

ON CONFLICT (activity_id, skill_id) DO NOTHING;

COMMIT;